#!/usr/bin/env python
"""Generate replay sidecars for a directory of clip .bk2 files.

Given any directory containing clip ``.bk2`` files, this script replays
each one and writes the per-clip sidecars next to it:

- ``_recording.mp4`` — video of the clip (with audio)
- ``.state`` — gzipped emulator RAM at clip entry
- ``_variables.json`` — frame-by-frame game variables
- ``{sub}_{ses}_summary.json`` — per-session JSON array of all clip metadata

The script is source-agnostic: it works on the clip ``.bk2`` files
produced by ``generate_clips.py`` as well as on clips generated by
artificial agents.  When a ``clips_manifest.tsv`` (written by
``generate_clips.py``) is found, the scene-detection metadata it carries
(``Outcome``, ``Phase``, ``SourceBk2``) is merged into each clip's entry;
without it, those fields are simply omitted.

One consolidated summary JSON is written per session at
``sub-XX/ses-YYY/sub-XX_ses-YYY_summary.json`` (outside ``gamelogs/``),
so it remains accessible without decompressing the archive.

Usage::

    python generate_replays.py -i /path/to/clips_dir -nj 1 -v
"""

import argparse
import gzip
import json
import logging
import os
import os.path as op
import traceback

import pandas as pd
import stable_retro as retro
from joblib import Parallel, delayed
from tqdm import tqdm
from tqdm_joblib import tqdm_joblib
from videogames_utils.replay import replay_bk2, reformat_info, assemble_audio
from videogames_utils.video import make_mp4

import sys
sys.path.insert(0, op.dirname(op.dirname(op.abspath(__file__))))
from utils import compute_clip_stats

GAME_NAME = "SuperMarioBros-Nes"
MANIFEST_NAME = "clips_manifest.tsv"


# ---------------------------------------------------------------------------
# Filename / clip-code parsing
# ---------------------------------------------------------------------------

def _parse_bids_entities(filename):
    """Extract BIDS-style ``key-value`` entities from a filename.

    Returns a dict, e.g. ``{"sub": "01", "ses": "001", "level": "w1l1"}``.
    Tolerant of non-BIDS filenames — unknown parts are simply ignored.
    """
    stem = op.basename(filename).rsplit(".", 1)[0]
    entities = {}
    for part in stem.split("_"):
        if "-" in part:
            key, value = part.split("-", 1)
            entities[key] = value
    return entities


def _decode_clip_code(clip_code):
    """Decode a 14-character clip code ``SSSRRBBNNNNNNN``.

    Returns ``{"session", "run", "rep_index", "start_frame"}`` or an empty
    dict when *clip_code* is not a 14-digit numeric string.
    """
    if not (isinstance(clip_code, str) and len(clip_code) == 14
            and clip_code.isdigit()):
        return {}
    return {
        "session": clip_code[0:3],
        "run": clip_code[3:5],
        "rep_index": int(clip_code[5:7]),
        "start_frame": int(clip_code[7:14]),
    }


# ---------------------------------------------------------------------------
# Manifest loading
# ---------------------------------------------------------------------------

def load_manifest(input_dir, manifest_arg=None):
    """Load ``clips_manifest.tsv`` keyed by ``clip_code``.

    Looks for an explicit *manifest_arg* path first, then for a
    ``clips_manifest.tsv`` in *input_dir* or any of its parent
    directories.  Returns an empty dict when none is found.
    """
    path = None
    if manifest_arg:
        path = op.abspath(manifest_arg)
    else:
        search = op.abspath(input_dir)
        while True:
            candidate = op.join(search, MANIFEST_NAME)
            if op.exists(candidate):
                path = candidate
                break
            parent = op.dirname(search)
            if parent == search:
                break
            search = parent

    if path is None or not op.exists(path):
        logging.info("No clips_manifest.tsv found — proceeding without it.")
        return {}

    logging.info(f"Manifest: {path}")
    df = pd.read_table(path, dtype={"clip_code": str})
    return {row["clip_code"]: row for row in df.to_dict("records")}


# ---------------------------------------------------------------------------
# Sidecar paths
# ---------------------------------------------------------------------------

def _sidecar_paths(bk2_path):
    """Return the four sidecar output paths for a clip .bk2."""
    base = bk2_path[:-4] if bk2_path.endswith(".bk2") else bk2_path
    return {
        "mp4": f"{base}_recording.mp4",
        "state": f"{base}.state",
        "variables": f"{base}_variables.json",
        "summary": f"{base}_summary.json",
    }


SIDECAR_KEYS = ("mp4", "state", "variables")


def _sidecars_exist(paths, skips):
    """Return True if all non-skipped sidecars already exist.

    When every per-clip sidecar is skipped (e.g. summary-only migration run),
    returns True if there is at least one source to recover the summary from
    (existing ``_variables.json`` or legacy ``_summary.json``), avoiding an
    unnecessary full replay.
    """
    keys = [k for k in SIDECAR_KEYS if not skips[k]]
    if not keys:
        return op.exists(paths["variables"]) or op.exists(paths["summary"])
    return all(op.exists(paths[k]) for k in keys)


# ---------------------------------------------------------------------------
# Summary metadata
# ---------------------------------------------------------------------------

def _build_summary(bk2_path, n_frames, clip_stats, manifest_row):
    """Assemble the ``_summary.json`` content for one clip.

    Combines entities parsed from the filename, the clip code, the replay
    (``n_frames``), gameplay *clip_stats*, and — when available — the
    scene-detection *manifest_row*.
    """
    entities = _parse_bids_entities(bk2_path)
    clip_code = entities.get("clip")
    decoded = _decode_clip_code(clip_code)

    summary = {"GameName": GAME_NAME}

    if "sub" in entities:
        summary["Subject"] = entities["sub"]
    if "ses" in entities:
        summary["Session"] = entities["ses"]
    if "level" in entities:
        summary["Level"] = entities["level"]
    if "level" in entities and "scene" in entities:
        summary["SceneID"] = f"{entities['level']}s{entities['scene']}"
    if clip_code:
        summary["ClipCode"] = clip_code
    if "run" in decoded:
        summary["Run"] = decoded["run"]

    # Frame range: clip code gives the start, the replay gives the length.
    start_frame = decoded.get("start_frame", 0)
    summary["StartFrame"] = int(start_frame)
    summary["EndFrame"] = int(start_frame + n_frames)
    summary["Duration"] = round(n_frames / 60, 3)

    # Scene-detection metadata that cannot be recovered from a .bk2 alone —
    # only present when the manifest is found. Entity fields (Run, Level,
    # SceneID, StartFrame) are left as derived from the filename / clip code.
    if manifest_row is not None:
        for src, dst in (("outcome", "Outcome"), ("phase", "Phase"),
                         ("source_bk2", "SourceBk2")):
            val = manifest_row.get(src)
            if pd.notna(val):
                summary[dst] = val

    if clip_stats:
        summary.update(clip_stats)

    return summary


def _load_skipped_summary(bk2_path, paths, manifest):
    """Return a summary dict for a clip whose sidecars already exist.

    Tries to recompute from the existing ``_variables.json`` first (most
    accurate), then falls back to reading a legacy per-clip ``_summary.json``
    if one is present.  Returns ``None`` when neither source is available.
    """
    if op.exists(paths["variables"]):
        try:
            with open(paths["variables"]) as f:
                clip_vars = json.load(f)
            n_frames = max(
                (len(v) for v in clip_vars.values() if isinstance(v, list)),
                default=0,
            )
            clip_code = _parse_bids_entities(bk2_path).get("clip")
            manifest_row = manifest.get(clip_code) if clip_code else None
            clip_stats = compute_clip_stats(clip_vars)
            return _build_summary(bk2_path, n_frames, clip_stats, manifest_row)
        except Exception:
            pass
    if op.exists(paths["summary"]):
        try:
            with open(paths["summary"]) as f:
                return json.load(f)
        except Exception:
            pass
    return None


def _session_summary_path(input_dir, sub, ses):
    """Return the output path for a per-session consolidated summary.

    Written at sub-XX/ses-YYY/ (outside gamelogs/) so it stays accessible
    without decompressing the archive.  Falls back to input_dir root for
    data that lacks sub/ses entities.
    """
    if sub and ses:
        return op.join(input_dir, f"sub-{sub}", f"ses-{ses}",
                       f"sub-{sub}_ses-{ses}_summary.json")
    return op.join(input_dir, "summary.json")


# ---------------------------------------------------------------------------
# Per-clip processing
# ---------------------------------------------------------------------------

def process_clip(bk2_path, stimuli_path, manifest, skips,
                 skip_first_step, overwrite):
    """Replay one clip .bk2 and write its sidecars.

    *skips* is a dict with keys ``"mp4"``, ``"state"``, ``"variables"``,
    ``"summary"``.  ``True`` means that sidecar is not written / not
    included in the consolidated summary.

    Returns
    -------
    tuple
        ``(error_logs, status, summary)`` where *status* is
        ``"processed"``, ``"skipped"`` or ``"error"`` and *summary* is
        the clip metadata dict (or ``None`` when ``--skip_summary`` is set
        or the summary could not be recovered).
    """
    retro.data.Integrations.add_custom_path(stimuli_path)
    error_logs = []

    try:
        paths = _sidecar_paths(bk2_path)
        if not overwrite and _sidecars_exist(paths, skips):
            logging.debug(f"Skipping (sidecars exist): {bk2_path}")
            summary = (
                None if skips["summary"]
                else _load_skipped_summary(bk2_path, paths, manifest)
            )
            return error_logs, "skipped", summary

        logging.info(f"Replaying: {bk2_path}")

        all_frames = []
        all_keys = []
        all_info = []
        all_states = []
        audio_chunks = []
        audio_rate = 0
        actions = None

        for frame, keys, annotations, audio_chunk, chunk_rate, _, acts, state \
                in replay_bk2(
                    bk2_path,
                    skip_first_step=skip_first_step,
                    game=GAME_NAME,
                    inttype=retro.data.Integrations.CUSTOM_ONLY,
                ):
            all_frames.append(frame)
            all_keys.append(keys)
            all_info.append(annotations["info"])
            all_states.append(state)
            if audio_chunk.size:
                audio_chunks.append(audio_chunk)
            audio_rate = chunk_rate
            if actions is None:
                actions = acts

        if actions is None or not all_frames:
            logging.warning(f"Empty replay: {bk2_path}")
            return error_logs, "error", None

        rep_vars = reformat_info(all_info, all_keys, bk2_path, actions)
        full_audio = assemble_audio(audio_chunks)
        n_frames = len(all_frames)

        # Video (with audio)
        if not skips["mp4"]:
            clip_audio = full_audio if full_audio.size else None
            make_mp4(all_frames, paths["mp4"], audio=clip_audio,
                     sample_rate=audio_rate)

        # Savestate — gzipped emulator RAM at clip entry
        if not skips["state"]:
            with gzip.open(paths["state"], "wb") as fh:
                fh.write(all_states[0])

        # Frame-by-frame variables
        clip_vars = {k: v for k, v in rep_vars.items() if k is not None}
        if not skips["variables"]:
            with open(paths["variables"], "w") as f:
                json.dump(clip_vars, f)

        # Summary metadata + gameplay stats (collected for consolidated write)
        summary = None
        if not skips["summary"]:
            clip_code = _parse_bids_entities(bk2_path).get("clip")
            manifest_row = manifest.get(clip_code) if clip_code else None
            clip_stats = compute_clip_stats(clip_vars)
            summary = _build_summary(bk2_path, n_frames, clip_stats,
                                     manifest_row)

        return error_logs, "processed", summary

    except Exception as e:
        msg = f"Error replaying {bk2_path}: {e}\n{traceback.format_exc()}"
        logging.error(msg)
        error_logs.append(msg)
        return error_logs, "error", None


# ---------------------------------------------------------------------------
# Clip discovery
# ---------------------------------------------------------------------------

def find_clip_bk2(input_dir):
    """Recursively find clip .bk2 files under *input_dir*.

    Files ending in ``_recording.mp4`` companions are not relevant; any
    ``.bk2`` is treated as a clip to replay.
    """
    bk2_files = []
    for root, _, files in os.walk(input_dir):
        for fname in sorted(files):
            if fname.endswith(".bk2"):
                bk2_files.append(op.join(root, fname))
    return sorted(bk2_files)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main(args):
    """Run the replay-sidecar pipeline."""
    levels = {0: logging.WARNING, 1: logging.INFO}
    logging.basicConfig(
        level=levels.get(args.verbose, logging.DEBUG),
        format="%(levelname)s: %(message)s",
    )

    input_dir = op.abspath(args.input)
    if not op.isdir(input_dir):
        raise NotADirectoryError(f"Input directory not found: {input_dir}")

    if args.stimuli:
        stimuli_path = op.abspath(args.stimuli)
    else:
        raise SystemExit(
            "A stimuli/ path is required (-sp): it provides the game ROM "
            "and integration files needed to replay the .bk2 files."
        )

    retro.data.Integrations.add_custom_path(stimuli_path)
    logging.info(f"Input: {input_dir}")
    logging.info(f"Stimuli: {stimuli_path}")

    skips = {
        "mp4": args.skip_mp4,
        "state": args.skip_state,
        "variables": args.skip_variables,
        "summary": args.skip_summary,
    }
    generated = [k for k in SIDECAR_KEYS if not skips[k]]
    if not skips["summary"]:
        generated.append("summary (consolidated)")
    logging.info(f"Sidecars to generate: {', '.join(generated) or 'none'}")

    manifest = load_manifest(input_dir, args.manifest)
    bk2_files = find_clip_bk2(input_dir)
    logging.info(f"Found {len(bk2_files)} clip .bk2 files ({args.n_jobs} jobs)")

    with tqdm_joblib(tqdm(desc="Generating replays", total=len(bk2_files))):
        results = Parallel(n_jobs=args.n_jobs)(
            delayed(process_clip)(
                bk2, stimuli_path, manifest, skips,
                args.skip_first_step, args.overwrite,
            )
            for bk2 in bk2_files
        )

    n_processed = sum(1 for r in results if r[1] == "processed")
    n_skipped = sum(1 for r in results if r[1] == "skipped")
    n_errors = sum(1 for r in results if r[1] == "error")
    all_errors = [msg for r in results for msg in r[0]]

    if not skips["summary"]:
        all_summaries = [r[2] for r in results if r[2] is not None]
        by_session: dict[tuple, list] = {}
        for s in all_summaries:
            key = (s.get("Subject", ""), s.get("Session", ""))
            by_session.setdefault(key, []).append(s)
        for (sub, ses), session_summaries in sorted(by_session.items()):
            session_summaries.sort(key=lambda s: s.get("ClipCode", ""))
            out_path = _session_summary_path(input_dir, sub, ses)
            with open(out_path, "w") as f:
                json.dump(session_summaries, f, indent=4)
            logging.warning(f"Wrote {len(session_summaries)} clip summaries → {out_path}")

    logging.warning(
        f"Done: {n_processed} replays generated, "
        f"{n_skipped} skipped, {n_errors} errors."
    )
    if all_errors:
        log_path = op.join(input_dir, "replay_generation_errors.log")
        with open(log_path, "w") as f:
            f.write("\n".join(all_errors))
        logging.warning(f"Error log: {log_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate replay sidecars for a directory of clip .bk2 "
                    "files.",
    )
    parser.add_argument(
        "-i", "--input", required=True,
        help="Directory containing clip .bk2 files (searched recursively).",
    )
    parser.add_argument(
        "-sp", "--stimuli", required=True,
        help="Path to stimuli/ folder (game ROM, data.json, etc.).",
    )
    parser.add_argument(
        "-m", "--manifest", default=None,
        help="Path to clips_manifest.tsv. Defaults to auto-detection in the "
             "input directory or its parents.",
    )
    parser.add_argument(
        "--skip_mp4", action=argparse.BooleanOptionalAction, default=True,
        help="Skip writing per-clip _recording.mp4 files. On by default; "
             "pass --no-skip_mp4 to generate them.",
    )
    parser.add_argument(
        "--skip_state", action=argparse.BooleanOptionalAction, default=True,
        help="Skip writing per-clip .state files. On by default; "
             "pass --no-skip_state to generate them.",
    )
    parser.add_argument(
        "--skip_variables", action=argparse.BooleanOptionalAction, default=True,
        help="Skip writing per-clip _variables.json files. On by default; "
             "pass --no-skip_variables to generate them.",
    )
    parser.add_argument(
        "--skip_summary", action=argparse.BooleanOptionalAction, default=False,
        help="Skip writing the consolidated per-session summary JSON. Off by "
             "default (summary is generated); pass --skip_summary to skip it.",
    )
    parser.add_argument(
        "--skip_first_step", action=argparse.BooleanOptionalAction,
        default=True,
        help="Skip the first movie step when replaying. On by default: "
             "each clip .bk2 is independently recorded with its own reset, "
             "which adds one extra post-reset frame. Pass --no-skip_first_step "
             "to keep it.",
    )
    parser.add_argument(
        "--overwrite", action="store_true",
        help="Regenerate sidecars even when they already exist.",
    )
    parser.add_argument(
        "-nj", "--n_jobs", default=-1, type=int,
        help="Parallel jobs (-1 = all cores). Default: -1.",
    )
    parser.add_argument(
        "-v", "--verbose", action="count", default=0,
        help="Increase verbosity (-v = INFO, -vv = DEBUG).",
    )
    main(parser.parse_args())
